import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Dialogs
import Quickshell
import Quickshell.Io
import qs.Common
import qs.Services
import qs.Widgets
import qs.Modules.Plugins

PluginComponent {
    id: root

    property var chatHistory: []
    property bool isRequesting: false
    property bool isProcessingFile: false

    // Window Sizing
    property int userWidth: 460
    property int userHeight: 540
    property bool isMaximized: false
    property bool hasManualResize: false

    // Attachment State
    property bool hasAttachment: false
    property string attachedFileName: ""
    property string attachedFileSize: ""
    property string attachedMimeType: ""
    property string attachedImagePath: ""
    property string currentBase64Payload: ""
    property bool attachedIsImage: false
    property string copyFeedback: ""

    property string configPath: Quickshell.env("HOME") + "/.config/DankMaterialShell/gemini_config.json"
    property var configData: ({ "apiKey": "", "model": "gemini-3.6-flash", "systemPrompt": "You are an expert desktop assistant on Linux. When given an image, code, or document, directly analyze and answer questions about it." })

    FileView {
        id: configFile
        path: root.configPath
        watchChanges: true
        onLoaded: {
            try {
                root.configData = JSON.parse(text());
            } catch (e) {
                appendSystemError("Failed to parse config file: " + e.message);
            }
        }
    }

    // 30-Second API Request Watchdog
    Timer {
        id: requestTimeoutTimer
        interval: 30000
        repeat: false
        onTriggered: {
            if (root.isRequesting) {
                root.isRequesting = false;
                appendSystemError("Request timed out. Google's servers took too long to respond. Please check your internet connection.");
            }
        }
    }

    // Reads atomic JSON output generated by the inline Python helper
    FileView {
        id: attachmentJsonReader
        watchChanges: true
        onLoaded: {
            try {
                var content = text().trim();
                if (!content) return;
                var data = JSON.parse(content);
                root.attachedFileName = data.name || "Attached File";
                root.attachedFileSize = data.size || "Unknown size";
                root.attachedMimeType = data.mime || "application/octet-stream";
                root.attachedIsImage = !!data.isImage;
                root.attachedImagePath = data.imagePath || "";
                root.currentBase64Payload = data.b64 || "";
                root.hasAttachment = true;
                root.isProcessingFile = false;
            } catch (e) {
                root.isProcessingFile = false;
                appendSystemError("Attachment read error: " + e.message);
            }
        }
    }

    FileDialog {
        id: filePicker
        title: "Select file to attach to Gemini"
        onAccepted: {
            var path = selectedFile.toString();
            if (path.startsWith("file://")) {
                path = decodeURIComponent(path.substring(7));
            }
            processFileWithInlinePython(path);
        }
        onRejected: {
            root.isProcessingFile = false;
        }
    }

    // Universal inline Python processor: eliminates external helper scripts
    Process {
        id: inlinePythonAttachProc
        onExited: (code, status) => {
            if (code === 0) {
                attachmentJsonReader.path = "";
                attachmentJsonReader.path = "/tmp/dms_gemini_attach.json";
            } else {
                root.isProcessingFile = false;
                if (code === 127) {
                    appendSystemError("Python 3 not found. Please install python on your system.");
                } else {
                    appendSystemError("Failed to process file (code " + code + ").");
                }
            }
        }
    }

    function processFileWithInlinePython(filePath) {
        if (!filePath) return;
        root.isProcessingFile = true;

        var pyCode =
        "import sys, os, json, mimetypes, base64\n" +
        "p = os.path.abspath(sys.argv[1])\n" +
        "if not os.path.isfile(p): sys.exit(1)\n" +
        "sz = os.path.getsize(p)\n" +
        "s_str = f'{sz} B' if sz < 1024 else (f'{sz/1024:.1f} KB' if sz < 1048576 else f'{sz/1048576:.1f} MB')\n" +
        "fn = os.path.basename(p)\n" +
        "m, _ = mimetypes.guess_type(p)\n" +
        "if not m:\n" +
        "    exts = ('.kdl', '.conf', '.sh', '.bash', '.zsh', '.fish', '.py', '.qml', '.json', '.toml', '.yaml', '.yml', '.txt', '.log', '.md', '.c', '.cpp', '.rs', '.go', '.js', '.ts', '.html', '.css')\n" +
        "    m = 'text/plain' if fn.lower().endswith(exts) else 'application/octet-stream'\n" +
        "with open(p, 'rb') as f: b64 = base64.b64encode(f.read()).decode('utf-8')\n" +
        "is_img = m.startswith('image/')\n" +
        "res = {'name': fn, 'size': s_str, 'mime': m, 'isImage': is_img, 'imagePath': ('file://' + p) if is_img else '', 'b64': b64}\n" +
        "with open('/tmp/dms_gemini_attach.json', 'w', encoding='utf-8') as out:\n" +
        "    json.dump(res, out, ensure_ascii=False)\n" +
        "    out.flush()\n" +
        "    os.fsync(out.fileno())\n" +
        "sys.exit(0)\n";

        inlinePythonAttachProc.exec(["python3", "-c", pyCode, filePath]);
    }

    Process {
        id: fullScreenProc
        onExited: (code, status) => {
            if (code === 0) {
                processFileWithInlinePython("/tmp/dms_gemini_shot.jpg");
            } else {
                root.isProcessingFile = false;
                appendSystemError("Screen capture failed (code " + code + "). Ensure 'grim' is installed.");
            }
        }
    }

    function captureFullScreen() {
        root.isProcessingFile = true;
        var cmd = "rm -f /tmp/dms_gemini_shot.jpg && grim -t jpeg -q 75 /tmp/dms_gemini_shot.jpg";
        fullScreenProc.exec(["sh", "-c", cmd]);
    }

    function discardAttachment() {
        root.hasAttachment = false;
        root.attachedFileName = "";
        root.attachedFileSize = "";
        root.attachedMimeType = "";
        root.attachedImagePath = "";
        root.currentBase64Payload = "";
        root.attachedIsImage = false;
    }

    Process {
        id: saveKeyProcess
    }

    function saveApiKeyDirectly(key) {
        if (!key || key.length < 15) {
            appendSystemError("Invalid API key format. Google AI Studio keys typically begin with 'AIzaSy'.");
            return;
        }
        root.configData.apiKey = key;
        var jsonStr = JSON.stringify(root.configData, null, 2);
        saveKeyProcess.exec(["sh", "-c", "mkdir -p ~/.config/DankMaterialShell && printf '%s' " + Qt.btoa(jsonStr) + " | base64 -d > " + root.configPath]);
        appendMessage("System", "✓ API key saved successfully!", null, false);
    }

    Process {
        id: copyProcess
    }

    function copyToClipboard(content, index) {
        if (!content) return;
        copyProcess.exec(["sh", "-c", "printf '%s' " + Qt.btoa(content) + " | base64 -d | wl-copy"]);
        root.copyFeedback = "copied_" + index;
        feedbackTimer.restart();
    }

    Timer {
        id: feedbackTimer
        interval: 1800
        onTriggered: root.copyFeedback = ""
    }

    function appendSystemError(errorText) {
        appendMessage("Error", errorText, null, true);
    }

    function parseGeminiError(status, responseText) {
        if (status === 0) {
            return "Cannot reach Google's servers. Please check your internet connection or DNS settings.";
        }
        if (status === 401 || status === 403) {
            return "Invalid or unauthorized API key (HTTP " + status + "). Set your key with: /key YOUR_API_KEY";
        }
        if (status === 404) {
            return "Model not found (HTTP 404). Update your model name in ~/.config/DankMaterialShell/gemini_config.json to 'gemini-3.6-flash'.";
        }
        if (status === 429) {
            return "Rate limit / Quota exceeded (HTTP 429). Google's free tier rate limit was reached. Please wait a moment.";
        }
        if (status >= 500) {
            return "Google Gemini servers are temporarily unavailable (HTTP " + status + "). Please try again shortly.";
        }

        try {
            var parsed = JSON.parse(responseText);
            if (parsed && parsed.error && parsed.error.message) {
                return "API Error (" + status + "): " + parsed.error.message;
            }
        } catch (e) {}

        return "HTTP Error " + status + ": " + responseText.substring(0, 200);
    }

    function sendPrompt(inputRef) {
        var text = inputRef.text.trim();
        if (text === "" && !root.hasAttachment) return;
        if (root.isRequesting) return;

        if (text.startsWith("/key ")) {
            saveApiKeyDirectly(text.substring(5).trim());
            inputRef.text = "";
            return;
        }

        var apiKey = (root.configData && root.configData.apiKey) ? root.configData.apiKey.trim() : "";
        if (!apiKey) {
            appendSystemError("No API key configured. Enter your key by typing: /key YOUR_API_KEY");
            return;
        }

        var modelName = (root.configData && root.configData.model) ? root.configData.model.trim() : "gemini-3.6-flash";
        var promptText = text !== "" ? text : "Please examine and explain this attached file.";

        var uiAttachment = null;
        var userParts = [];

        if (root.hasAttachment && root.currentBase64Payload !== "") {
            userParts.push({
                "inlineData": {
                    "mimeType": root.attachedMimeType || "application/octet-stream",
                    "data": root.currentBase64Payload
                }
            });

            uiAttachment = {
                "name": root.attachedFileName,
                "size": root.attachedFileSize,
                "isImage": root.attachedIsImage,
                "imagePath": root.attachedImagePath
            };

            discardAttachment();
        }

        userParts.push({ "text": promptText });

        appendMessage("User", promptText, uiAttachment, false);
        inputRef.text = "";
        root.isRequesting = true;
        requestTimeoutTimer.restart();

        var contentsPayload = [];
        for (var i = 0; i < root.chatHistory.length - 1; i++) {
            var entry = root.chatHistory[i];
            if (entry.isError) continue;
            if (entry.sender === "User") {
                contentsPayload.push({ "role": "user", "parts": [{ "text": entry.text }] });
            } else if (entry.sender === "Gemini") {
                contentsPayload.push({ "role": "model", "parts": [{ "text": entry.text }] });
            }
        }

        contentsPayload.push({ "role": "user", "parts": userParts });

        var reqBody = {
            "contents": contentsPayload,
            "systemInstruction": {
                "parts": [{ "text": (root.configData && root.configData.systemPrompt) ? root.configData.systemPrompt : "You are an expert desktop assistant on Linux. When given an image, code, or document, directly analyze and answer questions about it." }]
            }
        };

        var xhr = new XMLHttpRequest();
        var url = "https://generativelanguage.googleapis.com/v1beta/models/" + encodeURIComponent(modelName) + ":generateContent?key=" + encodeURIComponent(apiKey);

        xhr.open("POST", url, true);
        xhr.setRequestHeader("Content-Type", "application/json");

        xhr.onerror = function() {
            requestTimeoutTimer.stop();
            root.isRequesting = false;
            appendSystemError("Network error: Could not connect to Google AI API.");
        };

        xhr.onreadystatechange = function() {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                requestTimeoutTimer.stop();
                root.isRequesting = false;
                if (xhr.status === 200) {
                    try {
                        var res = JSON.parse(xhr.responseText);
                        if (res.candidates && res.candidates.length > 0) {
                            var candidate = res.candidates[0];
                            if (candidate.finishReason === "SAFETY") {
                                appendSystemError("The response was blocked by Google's safety guidelines.");
                                return;
                            }
                            if (candidate.content && candidate.content.parts && candidate.content.parts.length > 0) {
                                var reply = candidate.content.parts[0].text;
                                appendMessage("Gemini", reply, null, false);
                                return;
                            }
                        }
                        if (res.promptFeedback && res.promptFeedback.blockReason) {
                            appendSystemError("Prompt was blocked by Google: " + res.promptFeedback.blockReason);
                            return;
                        }
                        appendSystemError("Received an empty response from Gemini.");
                    } catch (e) {
                        appendSystemError("Failed to parse API response: " + e.message);
                    }
                } else {
                    var errorMsg = parseGeminiError(xhr.status, xhr.responseText);
                    appendSystemError(errorMsg);
                }
            }
        };

        try {
            xhr.send(JSON.stringify(reqBody));
        } catch (err) {
            requestTimeoutTimer.stop();
            root.isRequesting = false;
            appendSystemError("Request dispatch failed: " + err.message);
        }
    }

    function appendMessage(sender, text, attachment, isError) {
        var updated = root.chatHistory.slice();
        updated.push({
            "sender": sender,
            "text": text,
            "attachment": attachment,
            "isError": !!isError
        });
        root.chatHistory = updated;
    }

    // Horizontal bar pill
    horizontalBarPill: Component {
        Item {
            implicitWidth: pillRow.implicitWidth + 14
            implicitHeight: 28

            RowLayout {
                id: pillRow
                anchors.centerIn: parent
                spacing: 5

                Text {
                    text: "✦"
                    font.pixelSize: 13
                    color: Theme.primary
                }

                Text {
                    text: "Gemini"
                    font.pixelSize: 12
                    font.weight: Font.Medium
                    color: Theme.onSurface
                }
            }
        }
    }

    // Vertical bar pill
    verticalBarPill: Component {
        Item {
            implicitWidth: 28
            implicitHeight: 28
            Text {
                anchors.centerIn: parent
                text: "✦"
                font.pixelSize: 14
                color: Theme.primary
            }
        }
    }

    // Universal Popout Card
    popoutContent: Component {
        Rectangle {
            id: mainCard

            implicitWidth: root.isMaximized
            ? 720
            : (root.hasManualResize ? root.userWidth : 460)

            implicitHeight: root.isMaximized
            ? 800
            : (root.hasManualResize ? root.userHeight : (root.chatHistory.length === 0 && !root.hasAttachment ? 220 : 540))

            color: Theme.surfaceContainer
            radius: 22
            border.color: Qt.rgba(Theme.outline.r, Theme.outline.g, Theme.outline.b, 0.2)
            border.width: 1
            clip: true

            ColumnLayout {
                anchors.fill: parent
                anchors.margins: 14
                spacing: 10

                // Header
                RowLayout {
                    Layout.fillWidth: true
                    spacing: 8

                    Rectangle {
                        width: 30
                        height: 30
                        radius: 15
                        color: Theme.primaryContainer

                        Text {
                            anchors.centerIn: parent
                            text: "✦"
                            font.pixelSize: 14
                            color: Theme.onPrimaryContainer
                        }
                    }

                    ColumnLayout {
                        spacing: 1
                        Text {
                            text: "Gemini AI"
                            font.pixelSize: 14
                            font.weight: Font.DemiBold
                            color: Theme.onSurface
                        }
                        Text {
                            text: (root.configData && root.configData.model) ? root.configData.model : "gemini-3.6-flash"
                            font.pixelSize: 10
                            font.weight: Font.Medium
                            color: Theme.primary
                        }
                    }

                    Item { Layout.fillWidth: true }

                    // Expand / Restore Button
                    Rectangle {
                        width: 28
                        height: 28
                        radius: 14
                        color: expHover.hovered ? Theme.surfaceContainerHighest : "transparent"

                        Text {
                            anchors.centerIn: parent
                            text: root.isMaximized ? "⤡" : "⤢"
                            font.pixelSize: 12
                            color: Theme.onSurfaceVariant
                        }

                        HoverHandler { id: expHover }
                        MouseArea {
                            anchors.fill: parent
                            cursorShape: Qt.PointingHandCursor
                            onClicked: root.isMaximized = !root.isMaximized
                        }
                    }

                    // Clear button
                    Rectangle {
                        width: 28
                        height: 28
                        radius: 14
                        color: clrHover.hovered ? Theme.surfaceContainerHighest : "transparent"

                        Text {
                            anchors.centerIn: parent
                            text: "✕"
                            font.pixelSize: 12
                            color: Theme.onSurfaceVariant
                        }

                        HoverHandler { id: clrHover }
                        MouseArea {
                            anchors.fill: parent
                            cursorShape: Qt.PointingHandCursor
                            onClicked: {
                                root.chatHistory = [];
                                root.discardAttachment();
                                root.hasManualResize = false;
                            }
                        }
                    }
                }

                // Empty State Quick Prompts
                RowLayout {
                    visible: root.chatHistory.length === 0
                    Layout.fillWidth: true
                    spacing: 8

                    Rectangle {
                        height: 28
                        radius: 14
                        color: Theme.surfaceContainerHigh
                        border.color: Qt.rgba(Theme.outlineVariant.r, Theme.outlineVariant.g, Theme.outlineVariant.b, 0.4)
                        border.width: 1
                        implicitWidth: qp1.implicitWidth + 18

                        Text {
                            id: qp1
                            anchors.centerIn: parent
                            text: "📸 Analyze Screen"
                            font.pixelSize: 11
                            font.weight: Font.Medium
                            color: Theme.onSurface
                        }
                        MouseArea {
                            anchors.fill: parent
                            cursorShape: Qt.PointingHandCursor
                            onClicked: {
                                root.captureFullScreen();
                                chatInput.text = "Explain what is on my screen.";
                            }
                        }
                    }

                    Rectangle {
                        height: 28
                        radius: 14
                        color: Theme.surfaceContainerHigh
                        border.color: Qt.rgba(Theme.outlineVariant.r, Theme.outlineVariant.g, Theme.outlineVariant.b, 0.4)
                        border.width: 1
                        implicitWidth: qp2.implicitWidth + 18

                        Text {
                            id: qp2
                            anchors.centerIn: parent
                            text: "📎 Inspect File"
                            font.pixelSize: 11
                            font.weight: Font.Medium
                            color: Theme.onSurface
                        }
                        MouseArea {
                            anchors.fill: parent
                            cursorShape: Qt.PointingHandCursor
                            onClicked: filePicker.open()
                        }
                    }
                }

                // Chat Messages List
                ListView {
                    id: chatView
                    visible: root.chatHistory.length > 0
                    Layout.fillWidth: true
                    Layout.fillHeight: true
                    clip: true
                    spacing: 12
                    model: root.chatHistory
                    onCountChanged: chatView.positionViewAtEnd()

                    delegate: ColumnLayout {
                        width: chatView.width
                        spacing: 4

                        RowLayout {
                            Layout.fillWidth: true
                            layoutDirection: modelData.sender === "User" ? Qt.RightToLeft : Qt.LeftToRight

                            Rectangle {
                                Layout.maximumWidth: chatView.width * 0.86
                                radius: 16

                                color: modelData.isError
                                ? Theme.errorContainer
                                : (modelData.sender === "User"
                                ? Theme.primary
                                : (modelData.sender === "System" ? Theme.surfaceContainerHigh : Theme.surfaceContainerHighest))

                                border.color: modelData.isError
                                ? Theme.error
                                : (modelData.sender === "Gemini" ? Qt.rgba(Theme.outlineVariant.r, Theme.outlineVariant.g, Theme.outlineVariant.b, 0.3) : "transparent")
                                border.width: 1
                                implicitWidth: Math.max(bubbleColumn.implicitWidth + 24, modelData.attachment ? 200 : 60)
                                implicitHeight: bubbleColumn.implicitHeight + 20

                                ColumnLayout {
                                    id: bubbleColumn
                                    anchors.fill: parent
                                    anchors.margins: 10
                                    spacing: 6

                                    // Attachment Display inside Bubble
                                    Rectangle {
                                        visible: !!modelData.attachment
                                        Layout.fillWidth: true
                                        implicitHeight: modelData.attachment && modelData.attachment.isImage ? 140 : 36
                                        radius: 10
                                        color: Qt.rgba(0, 0, 0, 0.25)
                                        clip: true

                                        Image {
                                            visible: !!(modelData.attachment && modelData.attachment.isImage)
                                            anchors.fill: parent
                                            cache: false
                                            source: (modelData.attachment && modelData.attachment.imagePath) ? modelData.attachment.imagePath : ""
                                            fillMode: Image.PreserveAspectCrop
                                        }

                                        RowLayout {
                                            visible: !(modelData.attachment && modelData.attachment.isImage)
                                            anchors.fill: parent
                                            anchors.margins: 8
                                            spacing: 6

                                            Text {
                                                text: "📎"
                                                font.pixelSize: 13
                                            }
                                            Text {
                                                Layout.fillWidth: true
                                                text: modelData.attachment ? (modelData.attachment.name + " (" + modelData.attachment.size + ")") : ""
                                                font.pixelSize: 11
                                                font.weight: Font.Medium
                                                color: Theme.onPrimary
                                                elide: Text.ElideMiddle
                                            }
                                        }
                                    }

                                    // Top Bar for Messages
                                    RowLayout {
                                        visible: modelData.sender !== "User"
                                        Layout.fillWidth: true

                                        Text {
                                            text: modelData.isError ? "⚠️ Error" : modelData.sender
                                            font.pixelSize: 10
                                            font.weight: Font.DemiBold
                                            color: modelData.isError ? Theme.onErrorContainer : (modelData.sender === "Gemini" ? Theme.primary : Theme.onSurfaceVariant)
                                        }

                                        Item { Layout.fillWidth: true }

                                        Rectangle {
                                            visible: modelData.sender === "Gemini"
                                            width: 48
                                            height: 20
                                            radius: 10
                                            color: copyHov.hovered ? Theme.primaryContainer : "transparent"

                                            Text {
                                                anchors.centerIn: parent
                                                text: root.copyFeedback === ("copied_" + index) ? "✓ Done" : "Copy"
                                                font.pixelSize: 10
                                                font.weight: Font.Medium
                                                color: root.copyFeedback === ("copied_" + index) ? Theme.primary : Theme.onSurfaceVariant
                                            }

                                            HoverHandler { id: copyHov }
                                            MouseArea {
                                                anchors.fill: parent
                                                cursorShape: Qt.PointingHandCursor
                                                onClicked: root.copyToClipboard(modelData.text, index)
                                            }
                                        }
                                    }

                                    TextEdit {
                                        Layout.fillWidth: true
                                        readOnly: true
                                        selectByMouse: true
                                        wrapMode: TextEdit.Wrap
                                        textFormat: TextEdit.MarkdownText
                                        text: modelData.text
                                        font.pixelSize: 12
                                        font.family: "Sans"
                                        color: modelData.isError
                                        ? Theme.onErrorContainer
                                        : (modelData.sender === "User" ? Theme.onPrimary : Theme.onSurface)
                                    }
                                }
                            }
                        }
                    }
                }

                // Loading Indicator
                RowLayout {
                    visible: root.isRequesting || root.isProcessingFile
                    Layout.fillWidth: true
                    spacing: 6

                    Text {
                        text: "✦"
                        font.pixelSize: 11
                        color: Theme.primary
                    }
                    Text {
                        text: root.isProcessingFile ? "Attaching file..." : "Gemini is analyzing..."
                        font.pixelSize: 11
                        font.italic: true
                        color: Theme.onSurfaceVariant
                    }
                }

                // Live Visual Attachment Preview Card
                Rectangle {
                    visible: root.hasAttachment
                    Layout.fillWidth: true
                    height: 56
                    radius: 12
                    color: Theme.surfaceContainerHighest
                    border.color: Theme.primary
                    border.width: 1

                    RowLayout {
                        anchors.fill: parent
                        anchors.margins: 6
                        spacing: 8

                        Rectangle {
                            visible: root.attachedIsImage
                            Layout.preferredWidth: 64
                            Layout.fillHeight: true
                            radius: 6
                            color: "black"
                            clip: true

                            Image {
                                anchors.fill: parent
                                cache: false
                                source: root.attachedImagePath
                                fillMode: Image.PreserveAspectCrop
                            }
                        }

                        Rectangle {
                            visible: !root.attachedIsImage
                            Layout.preferredWidth: 42
                            Layout.fillHeight: true
                            radius: 6
                            color: Theme.primaryContainer

                            Text {
                                anchors.centerIn: parent
                                text: "📄"
                                font.pixelSize: 18
                            }
                        }

                        ColumnLayout {
                            Layout.fillWidth: true
                            spacing: 1

                            Text {
                                text: root.attachedFileName
                                font.pixelSize: 11
                                font.weight: Font.DemiBold
                                color: Theme.onSurface
                                elide: Text.ElideMiddle
                                Layout.fillWidth: true
                            }
                            Text {
                                text: root.attachedFileSize + " • Ready to send"
                                font.pixelSize: 10
                                color: Theme.onSurfaceVariant
                            }
                        }

                        Rectangle {
                            width: 26
                            height: 26
                            radius: 13
                            color: discardHover.hovered ? Theme.errorContainer : Theme.surfaceContainerHigh

                            Text {
                                anchors.centerIn: parent
                                text: "✕"
                                font.pixelSize: 11
                                color: discardHover.hovered ? Theme.onErrorContainer : Theme.onSurfaceVariant
                            }

                            HoverHandler { id: discardHover }
                            MouseArea {
                                anchors.fill: parent
                                cursorShape: Qt.PointingHandCursor
                                onClicked: root.discardAttachment()
                            }
                        }
                    }
                }

                // Composer Input Capsule
                Rectangle {
                    id: composerCard
                    Layout.fillWidth: true
                    height: 48
                    radius: 24
                    color: Theme.surfaceContainerHigh
                    border.color: Qt.rgba(Theme.outlineVariant.r, Theme.outlineVariant.g, Theme.outlineVariant.b, 0.4)
                    border.width: 1

                    RowLayout {
                        anchors.fill: parent
                        anchors.leftMargin: 8
                        anchors.rightMargin: 6
                        spacing: 4

                        // Screenshot (📸)
                        Rectangle {
                            width: 34
                            height: 34
                            radius: 17
                            color: camHover.hovered ? Theme.surfaceContainerHighest : "transparent"

                            Text {
                                anchors.centerIn: parent
                                text: "📸"
                                font.pixelSize: 14
                            }

                            HoverHandler { id: camHover }
                            MouseArea {
                                anchors.fill: parent
                                cursorShape: Qt.PointingHandCursor
                                onClicked: root.captureFullScreen()
                            }
                        }

                        // Attachment (📎)
                        Rectangle {
                            width: 34
                            height: 34
                            radius: 17
                            color: attHover.hovered ? Theme.surfaceContainerHighest : "transparent"

                            Text {
                                anchors.centerIn: parent
                                text: "📎"
                                font.pixelSize: 14
                                color: Theme.onSurfaceVariant
                            }

                            HoverHandler { id: attHover }
                            MouseArea {
                                anchors.fill: parent
                                cursorShape: Qt.PointingHandCursor
                                onClicked: filePicker.open()
                            }
                        }

                        // Text Field
                        TextField {
                            id: chatInput
                            Layout.fillWidth: true
                            placeholderText: root.hasAttachment ? ("Ask about " + root.attachedFileName + "...") : "Ask Gemini..."
                            placeholderTextColor: Theme.onSurfaceVariant
                            font.pixelSize: 13
                            color: Theme.onSurface
                            background: null
                            onAccepted: root.sendPrompt(chatInput)
                        }

                        // Send Button
                        Rectangle {
                            width: 36
                            height: 36
                            radius: 18
                            color: (chatInput.text.trim() !== "" || root.hasAttachment) ? Theme.primary : Theme.surfaceContainerHighest

                            Text {
                                anchors.centerIn: parent
                                text: "➤"
                                font.pixelSize: 13
                                color: (chatInput.text.trim() !== "" || root.hasAttachment) ? Theme.onPrimary : Theme.outline
                            }

                            MouseArea {
                                anchors.fill: parent
                                cursorShape: Qt.PointingHandCursor
                                enabled: !root.isRequesting && (chatInput.text.trim() !== "" || root.hasAttachment)
                                onClicked: root.sendPrompt(chatInput)
                            }
                        }
                    }
                }
            }

            // Drag Resize Corner (Bottom-Right)
            Item {
                anchors.right: parent.right
                anchors.bottom: parent.bottom
                width: 22
                height: 22

                Text {
                    anchors.centerIn: parent
                    text: "⋰"
                    font.pixelSize: 12
                    color: Theme.outline
                }

                MouseArea {
                    anchors.fill: parent
                    cursorShape: Qt.SizeFDiagCursor
                    property point startPos

                    onPressed: (mouse) => {
                        startPos = Qt.point(mouse.x, mouse.y);
                        root.hasManualResize = true;
                    }

                    onPositionChanged: (mouse) => {
                        var dx = mouse.x - startPos.x;
                        var dy = mouse.y - startPos.y;

                        root.userWidth = Math.max(380, Math.min(960, mainCard.implicitWidth + dx));
                        root.userHeight = Math.max(220, Math.min(900, mainCard.implicitHeight + dy));
                    }
                }
            }
        }
    }
}
